services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1
    restart: unless-stopped
    ports:
      - 1411:1411
    volumes:
      - pocketid_data:/app/data


    environment:
      APP_URL: http://localhost:1411
      TRUST_PROXY: "false" # Set to true if Umbrel reverse proxy terminates TLS
      MAXMIND_LICENSE_KEY:
      PUID: "1000"
      PGID: "1000"
    labels:
      icon: https://pocket-id.org/img/logo.png
    # Optional healthcheck
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

volumes:
  pocketid_data:
